
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/team02-s24-5pm-3
owner: ucsb-cs156-s24
repo_name: team02-s24-5pm-3
pull_requests: [{"author":{"id":"U_kgDOBtxm2A","is_bot":false,"login":"sherpatran","name":""},"headRefName":"tt-MenuItemTable","number":51,"title":"Created Database for MenuItemReviews","url":"https://github.com/ucsb-cs156-s24/team02-s24-5pm-3/pull/51"},{"author":{"id":"U_kgDOB8qE7g","is_bot":false,"login":"tmcanepa","name":"Tyler Canepa"},"headRefName":"TylerC-RecReq-Controller","number":50,"title":"TylerC Finish RecommendationRequests","url":"https://github.com/ucsb-cs156-s24/team02-s24-5pm-3/pull/50"},{"author":{"id":"MDQ6VXNlcjQ5Nzc0NzYx","is_bot":false,"login":"Xalex217","name":""},"headRefName":"aaron-UCSBDiningCommonsMenuItem-create-db","number":49,"title":"Aaron ucsb dining commons menu item create db","url":"https://github.com/ucsb-cs156-s24/team02-s24-5pm-3/pull/49"},{"author":{"id":"U_kgDOB8qE7g","is_bot":false,"login":"tmcanepa","name":"Tyler Canepa"},"headRefName":"TylerC-RecommendationRequest-create-db","number":45,"title":"add Enitity, Repository, and Migration","url":"https://github.com/ucsb-cs156-s24/team02-s24-5pm-3/pull/45"}]
