
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/team02-s24-5pm-3
owner: ucsb-cs156-s24
repo_name: team02-s24-5pm-3
pull_requests: [{"author":{"id":"U_kgDOBXuyEw","is_bot":false,"login":"30912hyl","name":""},"headRefName":"Aaron-Articles-create-db","number":47,"title":"Created database for Articles","url":"https://github.com/ucsb-cs156-s24/team02-s24-5pm-3/pull/47"},{"author":{"id":"U_kgDOB8qE7g","is_bot":false,"login":"tmcanepa","name":"Tyler Canepa"},"headRefName":"TylerC-RecommendationRequest-create-db","number":45,"title":"add Enitity, Repository, and Migration","url":"https://github.com/ucsb-cs156-s24/team02-s24-5pm-3/pull/45"},{"author":{"id":"MDQ6VXNlcjQzNzgzODc3","is_bot":false,"login":"yuxiaolejs","name":"Unics Yu"},"headRefName":"Tianle-UCSBOrg","number":44,"title":"[merge] Finished UCSB Organizations","url":"https://github.com/ucsb-cs156-s24/team02-s24-5pm-3/pull/44"},{"author":{"id":"U_kgDOBXy3rA","is_bot":false,"login":"andrew-kwon1","name":""},"headRefName":"Andrew-HelpRequest-create-db","number":43,"title":"helprequest database","url":"https://github.com/ucsb-cs156-s24/team02-s24-5pm-3/pull/43"}]
